name: Selenium Test on Push

on:
  push:
    branches: [master]

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Composer dependencies
      run: |
        cp .env.example .env
        composer install
        php artisan key:generate

    - name: Start Laravel server
      run: |
        php -S 127.0.0.1:8000 -t public > /dev/null 2>&1 &
        sleep 5

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Selenium
      run: pip install selenium

    - name: Install Chrome & ChromeDriver
    run: |
      sudo apt-get update
      sudo apt-get install -y chromium-browser chromium-chromedriver
      sudo apt-get install -y unzip
      sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
      sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome

    - name: Run Selenium Test
      run: python tests/selenium_contact_form.py
